name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using private key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
                    cd /var/www/tanken.mkay-development.de/app && git pull && yarn build