name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        id: lighthouse-ci-report
        with:
          urls: |
            https://tanken.mkay-development.de/
          budgetPath: ./.github/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Get color
        run: echo "The selected color is ${{ steps.lighthouse-ci-report.outputs.links }}"
